"""Build the German, offline written-assignment report.

The quantitative content is generated by the same functions as the English
submission report.  Only presentation text is localized; company names,
official source titles, formulas, dataset identifiers and machine-readable
status codes remain unchanged so that both editions stay directly auditable.
"""

from __future__ import annotations

import html as html_module
import re

from pathlib import Path

from bokeh.embed import components
from bokeh.models import HoverTool

from src import build_written_assignment_report as english_report


OUTPUT_FILE = (
    english_report.ROOT
    / "output"
    / "black_doves_written_assignment_report_de.html"
)


def main():
    data = english_report._load_data()
    charts = english_report._create_charts(data)
    _localize_charts(charts)
    script, divs = components(charts)
    english_html = english_report._report_html(data, script, divs)
    german_html = _translate_document(english_html)
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    temporary = OUTPUT_FILE.with_suffix(".html.tmp")
    temporary.write_text(german_html, encoding="utf-8")
    temporary.replace(OUTPUT_FILE)
    print(OUTPUT_FILE)
    return 0


def _localize_charts(charts):
    chart_text = {
        "Post-event cumulative average abnormal return": (
            "Kumulierte durchschnittliche abnormale Rendite nach dem Ereignis"
        ),
        "Trading day relative to 2 March 2026": (
            "Handelstag relativ zum 2. März 2026"
        ),
        "CAAR from day 0 (%)": "CAAR ab Tag 0 (%)",
        "Long-horizon benchmark-relative performance": (
            "Benchmark-relative Wertentwicklung im langen Horizont"
        ),
        "Return difference / cumulative abnormal return (%)": (
            "Renditedifferenz / kumulierte abnormale Rendite (%)"
        ),
        "Brent and German fuel prices, indexed to first observation": (
            "Brent- und deutsche Kraftstoffpreise, indexiert auf die erste Beobachtung"
        ),
        "Observation date": "Beobachtungsdatum",
        "Index (first observation = 100)": "Index (erste Beobachtung = 100)",
        "Exploratory Brent-to-German-fuel associations": (
            "Explorative Zusammenhänge zwischen Brent und deutschen Kraftstoffpreisen"
        ),
        "Fuel-price lag after Brent week (weeks)": (
            "Verzögerung des Kraftstoffpreises nach der Brent-Woche (Wochen)"
        ),
        "Spearman correlation": "Spearman-Korrelation",
        "Confirmatory (n=8)": "Konfirmatorisch (n=8)",
        "Exploratory (n=37)": "Explorativ (n=37)",
        "BHAR (preferred long-horizon measure)": (
            "BHAR (bevorzugtes Langfristmaß)"
        ),
        "OLS CAR (sensitivity)": "OLS-CAR (Sensitivität)",
        "Brent crude": "Brent-Rohöl",
        "Diesel excl. taxes": "Diesel ohne Steuern",
        "Diesel incl. taxes": "Diesel einschließlich Steuern",
        "Petrol Euro 95 excl. taxes": "Benzin Euro 95 ohne Steuern",
        "Petrol Euro 95 incl. taxes": "Benzin Euro 95 einschließlich Steuern",
        "Diesel – With Tax": "Diesel – mit Steuern",
        "Diesel – Without Tax": "Diesel – ohne Steuern",
        "Petrol – With Tax": "Benzin – mit Steuern",
        "Petrol – Without Tax": "Benzin – ohne Steuern",
    }
    tooltip_labels = {
        "Sample": "Stichprobe",
        "Trading day": "Handelstag",
        "Company": "Unternehmen",
        "Observations": "Beobachtungen",
        "Series": "Reihe",
        "Date": "Datum",
        "Value": "Wert",
        "Index": "Index",
        "Lag": "Verzögerung",
        "Raw p": "Rohes p",
        "Holm p": "Holm-p",
    }

    for chart in charts.values():
        chart.title.text = chart_text.get(chart.title.text, chart.title.text)
        for axis in chart.axis:
            if axis.axis_label:
                axis.axis_label = chart_text.get(axis.axis_label, axis.axis_label)
        for legend in chart.legend:
            for item in legend.items:
                value = getattr(item.label, "value", None)
                if value in chart_text:
                    item.label = {"value": chart_text[value]}
        for tool in chart.tools:
            if not isinstance(tool, HoverTool) or not tool.tooltips:
                continue
            localized = []
            for label, value in tool.tooltips:
                value = chart_text.get(value, value).replace(" weeks", " Wochen")
                localized.append((tooltip_labels.get(label, label), value))
            tool.tooltips = localized
        for renderer in chart.renderers:
            source = getattr(renderer, "data_source", None)
            if source is None or "series_label" not in source.data:
                continue
            source.data["series_label"] = [
                chart_text.get(str(value), str(value))
                for value in source.data["series_label"]
            ]


def _translate_document(document):
    document = document.replace('<html lang="en">', '<html lang="de">', 1)
    protected = re.compile(
        r"(<(?:script|style)\b.*?</(?:script|style)>)",
        flags=re.IGNORECASE | re.DOTALL,
    )
    parts = protected.split(document)
    for index in range(0, len(parts), 2):
        parts[index] = re.sub(r">([^<>]+)<", _translate_node, parts[index])
    translated = "".join(parts)
    language_note = (
        '<p class="note"><strong>Sprachhinweis.</strong> Unternehmensnamen, '
        "Formeln, Datensatz-IDs, maschinenlesbare Statuscodes und verlinkte "
        "Originaltitel bleiben unverändert, damit die deutsche und die "
        "englische Fassung direkt überprüfbar bleiben.</p>"
    )
    translated = translated.replace("</header>", language_note + "\n</header>", 1)
    return re.sub(r"[ \t]+$", "", translated, flags=re.MULTILINE)


def _translate_node(match):
    original = match.group(1)
    leading = original[: len(original) - len(original.lstrip())]
    trailing = original[len(original.rstrip()) :]
    value = html_module.unescape(original.strip())
    translated = TRANSLATIONS.get(value)
    if translated is None:
        for pattern, replacement in REGEX_TRANSLATIONS:
            if pattern.fullmatch(value):
                translated = pattern.sub(replacement, value)
                break
    if translated is None:
        return ">" + original + "<"
    escaped = html_module.escape(translated, quote=False)
    return ">" + leading + escaped + trailing + "<"


TRANSLATIONS = {
    # Document, hero and navigation.
    "BLACK DOVES — Written Assignment Report": (
        "BLACK DOVES — Bericht zur schriftlichen Ausarbeitung"
    ),
    "BLACK DOVES / submission edition": "BLACK DOVES / Abgabeversion",
    "Tracing the Economic Effects of the 2026 Israel–Iran–United States Conflict": (
        "Nachzeichnung der wirtschaftlichen Auswirkungen des Konflikts zwischen "
        "Israel, Iran und den Vereinigten Staaten im Jahr 2026"
    ),
    "An object-oriented Python framework linking state roles, sectoral returns, Brent crude oil and German consumer fuel prices.": (
        "Ein objektorientiertes Python-Framework, das staatliche Rollen, "
        "Sektorrenditen, Brent-Rohöl und deutsche Kraftstoffpreise für "
        "Verbraucher miteinander verknüpft."
    ),
    "Core period · 1 Jan–18 Aug 2026": "Kernzeitraum · 1. Jan.–18. Aug. 2026",
    "Event · 28 Feb 2026": "Ereignis · 28. Feb. 2026",
    "Effective market date · 2 Mar 2026": "Effektiver Markttag · 2. März 2026",
    "8 confirmatory companies": "8 konfirmatorische Unternehmen",
    "37 exploratory controls": "37 explorative Kontrollunternehmen",
    "Offline Bokeh report": "Offline-Bokeh-Bericht",
    "Findings": "Ergebnisse",
    "Design": "Design",
    "State roles": "Staatliche Rollen",
    "Markets": "Märkte",
    "Energy": "Energie",
    "Dependency": "Abhängigkeit",
    "Ownership": "Eigentum",
    "Operations": "Operationen",
    "Methods": "Methoden",
    "Open questions": "Offene Fragen",
    "Audit": "Prüfung",
    # Findings.
    "Answer first": "Ergebnis vorweg",
    "What the evidence supports": "Was die Evidenz trägt",
    "Event-day AAR": "AAR am Ereignistag",
    "Specificity test": "Spezifitätstest",
    "Post-event BHAR": "BHAR nach dem Ereignis",
    "Core conclusion.": "Kernaussage.",
    "The pre-specified companies show a positive short-window market reaction, but the exploratory universe moved by a similar amount. The design therefore supports a broad conflict-period market association—not a company-selection-specific effect and not a causal estimate.": (
        "Die vorab festgelegten Unternehmen zeigen im kurzen Zeitfenster eine "
        "positive Marktreaktion; das explorative Universum bewegte sich jedoch in "
        "ähnlicher Größenordnung. Das Design stützt daher einen breiten "
        "Marktzusammenhang während des Konfliktzeitraums, nicht aber einen für die "
        "Unternehmensauswahl spezifischen Effekt und keine kausale Schätzung."
    ),
    "What the late evidence changes.": "Was die später ergänzte Evidenz verändert.",
    "It strengthens three contextual points without changing the core estimate: market-model betas differ sharply across firms; the 1–2 July defence rally was sector-wide rather than uniquely Rheinmetall; and a regulatory filing verifies a common BlackRock-managed ownership layer. The Pentagon production report is a credible timing anchor, but its 10 August return pattern is not specific to defence firms in this panel.": (
        "Sie stärkt drei Kontextbefunde, ohne die Kernschätzung zu verändern: Die "
        "Betas des Marktmodells unterscheiden sich deutlich zwischen den "
        "Unternehmen; die Rüstungsrally am 1.–2. Juli war sektorweit und nicht auf "
        "Rheinmetall beschränkt; und eine regulatorische Meldung bestätigt eine "
        "gemeinsame, von BlackRock verwaltete Eigentumsebene. Der "
        "Pentagon-Bericht zur Produktionsbeschleunigung ist ein glaubwürdiger "
        "zeitlicher Anker, doch das Renditemuster am 10. August ist in diesem "
        "Panel nicht rüstungsspezifisch."
    ),
    "Energy channel": "Energiekanal",
    "Dependency and operational record": "Abhängigkeit und Operationsnachweis",
    # Research design.
    "Research design": "Forschungsdesign",
    "Pre-specified event, transparent estimands": (
        "Vorab festgelegtes Ereignis, transparente Schätzgrößen"
    ),
    "The research question asks how direct participation, arms-supply context, political positioning and economic dependency were associated with company abnormal returns, Brent prices and German consumer fuel prices. Country roles overlap and are not collapsed into a single score. With only five focal countries, the role profile is qualitative context rather than a cross-country regression.": (
        "Die Forschungsfrage untersucht, wie direkte Beteiligung, der Kontext von "
        "Waffenlieferungen, politische Positionierung und wirtschaftliche "
        "Abhängigkeit mit abnormalen Unternehmensrenditen, Brent-Preisen und "
        "deutschen Kraftstoffpreisen für Verbraucher zusammenhingen. Die "
        "Länderrollen überschneiden sich und werden nicht zu einem einzigen Score "
        "verdichtet. Bei nur fünf Fokusländern dient das Rollenprofil als "
        "qualitativer Kontext und nicht als länderübergreifende Regression."
    ),
    "Event-study design": "Design der Ereignisstudie",
    "The calendar event is Saturday, 28 February 2026. Because markets were closed, the first effective trading date is Monday, 2 March. The confirmatory window is five trading days before through ten trading days after. The OLS single-factor market model uses all available pre-event observations from the downloaded history; this avoids look-ahead but has no pre-event gap.": (
        "Das Kalenderereignis fällt auf Samstag, den 28. Februar 2026. Da die "
        "Börsen geschlossen waren, ist Montag, der 2. März, der erste effektive "
        "Handelstag. Das konfirmatorische Fenster reicht von fünf Handelstagen vor "
        "bis zehn Handelstage nach dem Ereignis. Das einfaktorielle "
        "OLS-Marktmodell nutzt alle verfügbaren Beobachtungen vor dem Ereignis aus "
        "der heruntergeladenen Historie. Dadurch wird ein Zukunftsbias vermieden, "
        "allerdings ohne zeitlichen Abstand vor dem Ereignis."
    ),
    "Long horizon": "Langer Horizont",
    "For 2 March–18 August, BHAR is preferred because it compares compounded returns:": (
        "Für den Zeitraum vom 2. März bis 18. August wird BHAR bevorzugt, weil "
        "dieses Maß aufgezinst kumulierte Renditen vergleicht:"
    ),
    "CAR remains as a sensitivity metric, not the headline long-run measure.": (
        "CAR bleibt als Sensitivitätsmaß erhalten, ist aber nicht die zentrale "
        "Langfristkennzahl."
    ),
    "Market-data provenance correction.": "Korrektur der Marktdaten-Provenienz.",
    "The supplied files were downloaded through": "Die bereitgestellten Dateien wurden über",
    "/Yahoo Finance for exchange-listed instruments; they are not direct files from Nasdaq, Xetra or TASE. The report labels them accordingly. A final university submission should replace or independently verify these snapshots if the approved proposal strictly requires official-exchange delivery.": (
        "/Yahoo Finance für börsennotierte Instrumente heruntergeladen; es sind "
        "keine direkt von Nasdaq, Xetra oder TASE bezogenen Dateien. Der Bericht "
        "kennzeichnet sie entsprechend. Falls der genehmigte Vorschlag zwingend "
        "eine Bereitstellung durch die offiziellen Börsen verlangt, sollten diese "
        "Momentaufnahmen vor der endgültigen Hochschulabgabe ersetzt oder "
        "unabhängig verifiziert werden."
    ),
    "Direct Israel–Germany channel not identified.": (
        "Direkter Israel–Deutschland-Kanal nicht identifiziert."
    ),
    "Israeli decisions and German market outcomes are present as separate evidence layers, but no pre-specified Israeli announcement series is linked to German target assets. A bilateral claim would require a separate event design with verified timestamps, German securities and benchmarks, and controls for oil, interest rates and sector-wide defence news. Parallel narratives are not evidence of a direct effect.": (
        "Israelische Entscheidungen und deutsche Marktergebnisse liegen als "
        "getrennte Evidenzebenen vor; eine vorab festgelegte Reihe israelischer "
        "Ankündigungen ist jedoch nicht mit deutschen Zielwerten verknüpft. Eine "
        "bilaterale Aussage würde ein eigenes Ereignisdesign mit verifizierten "
        "Zeitpunkten, deutschen Wertpapieren und Benchmarks sowie Kontrollen für "
        "Öl, Zinsen und sektorweite Rüstungsnachrichten erfordern. Parallele "
        "Erzählstränge sind kein Beleg für einen direkten Effekt."
    ),
    "The endpoint remains 18 August 2026 even though some raw market histories continue to 2 September and supplied media files to 14 September. Moving the endpoint after inspecting later dramatic stories would alter the approved design.": (
        "Der Endpunkt bleibt der 18. August 2026, obwohl einige rohe "
        "Marktzeitreihen bis zum 2. September und bereitgestellte Mediendateien bis "
        "zum 14. September reichen. Eine nachträgliche Verschiebung des Endpunkts "
        "nach Sichtung späterer dramatischer Meldungen würde das genehmigte Design "
        "verändern."
    ),
    "UCDP scope": "Geltungsbereich von UCDP",
    "UCDP terminology supplies the conflict-definition and historical-actor framework promised in the proposal. The annual UCDP/PRIO and Actor releases are catalogued as version 26.1, but no UCDP row enters the 2026 statistical analysis. The focal event and country roles are therefore researcher-specified from dated official statements, not presented as UCDP-coded observations.": (
        "Die UCDP-Terminologie liefert den im Themenvorschlag angekündigten Rahmen "
        "für Konfliktdefinitionen und historische Akteure. Die jährlichen "
        "UCDP/PRIO- und Actor-Veröffentlichungen sind als Version 26.1 "
        "katalogisiert; keine UCDP-Zeile geht jedoch in die statistische Analyse "
        "für 2026 ein. Das Fokusereignis und die Länderrollen wurden daher anhand "
        "datierter offizieller Stellungnahmen durch den Forscher festgelegt und "
        "werden nicht als UCDP-kodierte Beobachtungen dargestellt."
    ),
    # Common table headers and labels.
    "Resource": "Ressource",
    "Version / access": "Version / Zugriff",
    "Coverage": "Abdeckung",
    "Use": "Verwendung",
    "Source": "Quelle",
    "Boundary": "Abgrenzung",
    "official page": "offizielle Seite",
    "Multidimensional context": "Mehrdimensionaler Kontext",
    "Country-role profile": "Länderrollenprofil",
    "No role label is treated as mutually exclusive. Arms shares cover SIPRI major-arms transfers in 2021–25 and therefore establish pre-conflict exposure—not transfers made during the focal conflict.": (
        "Keine Rollenbezeichnung wird als gegenseitig ausschließend behandelt. Die "
        "Waffenanteile beziehen sich auf SIPRI-Transfers von Großwaffen im Zeitraum "
        "2021–2025 und bilden daher eine Exposition vor dem Konflikt ab, nicht "
        "Lieferungen während des untersuchten Konflikts."
    ),
    "Country": "Land",
    "Direct": "Direkt",
    "Arms context": "Waffenkontext",
    "Political position": "Politische Position",
    "Economic dependency": "Wirtschaftliche Abhängigkeit",
    "Evidence status": "Evidenzstatus",
    "YES": "JA",
    "NO": "NEIN",
    # Market section.
    "Market evidence": "Marktevidenz",
    "Short-window results are positive but not specific": (
        "Die Ergebnisse im kurzen Fenster sind positiv, aber nicht spezifisch"
    ),
    "The chart resets cumulative abnormal returns at trading day 0, avoiding contamination from the pre-event portion of the display window. Both samples rise together; the bootstrap difference interval includes zero for the event day, market-adjusted CAR and OLS CAR.": (
        "Das Diagramm setzt die kumulierten abnormalen Renditen am Handelstag 0 "
        "zurück und verhindert damit eine Vermischung mit dem Zeitraum vor dem "
        "Ereignis. Beide Stichproben steigen gemeinsam; das "
        "Bootstrap-Differenzintervall enthält für den Ereignistag, den "
        "marktbereinigten CAR und den OLS-CAR den Wert null."
    ),
    "Eight pre-specified companies": "Acht vorab festgelegte Unternehmen",
    "Company": "Unternehmen",
    "Role": "Rolle",
    "Event day": "Ereignistag",
    "Defence Contractor": "Rüstungsunternehmen",
    "Raw Materials & Energy": "Rohstoffe und Energie",
    "Market-model diagnostics: beta is not conflict sensitivity": (
        "Diagnostik des Marktmodells: Beta ist keine Konfliktsensitivität"
    ),
    "Pre-event beta measures historical co-movement with each company’s configured broad-market benchmark. Lockheed Martin, Northrop Grumman and RTX have low betas, but also very low R² values: the one-factor benchmark explains little of their daily return variation. Palantir and NVIDIA have betas above two and materially higher R². This is precisely why a naive return-minus-index calculation and an OLS market model need to be shown separately; neither specification is automatically the truth.": (
        "Das Beta vor dem Ereignis misst die historische gemeinsame Bewegung mit "
        "der jeweils hinterlegten breiten Marktbenchmark. Lockheed Martin, "
        "Northrop Grumman und RTX weisen niedrige Betas, zugleich aber sehr niedrige "
        "R²-Werte auf: Die Einfaktor-Benchmark erklärt nur wenig von der täglichen "
        "Renditevariation. Palantir und NVIDIA besitzen Betas über zwei und deutlich "
        "höhere R²-Werte. Genau deshalb müssen eine einfache "
        "Rendite-minus-Index-Berechnung und ein OLS-Marktmodell getrennt ausgewiesen "
        "werden; keine der beiden Spezifikationen ist automatisch die Wahrheit."
    ),
    "Pre-event n": "n vor dem Ereignis",
    "Simple CAR": "Einfacher CAR",
    "OLS − simple": "OLS − einfach",
    "Interpretation.": "Interpretation.",
    "A low beta does not show that a defence firm is “war-sensitive but market-independent.” It shows low estimated broad-market loading in the pre-event window. When R² is near zero, residual returns can contain sector, company and other omitted shocks as well as any conflict-related component.": (
        "Ein niedriges Beta zeigt nicht, dass ein Rüstungsunternehmen "
        "„kriegssensitiv, aber marktunabhängig“ ist. Es zeigt eine niedrig "
        "geschätzte Belastung durch den breiten Markt im Fenster vor dem Ereignis. "
        "Liegt R² nahe null, können die Residualrenditen neben einem möglichen "
        "Konfliktanteil auch sektorale, unternehmensspezifische und andere nicht "
        "berücksichtigte Schocks enthalten."
    ),
    "Bootstrap intervals and between-sample differences": (
        "Bootstrap-Intervalle und Unterschiede zwischen den Stichproben"
    ),
    "Metric": "Kennzahl",
    "Estimate for": "Schätzung für",
    "Estimate": "Schätzung",
    "CI lower": "KI-Untergrenze",
    "CI upper": "KI-Obergrenze",
    "Interval status": "Intervallstatus",
    "Event-day abnormal return": "Abnormale Rendite am Ereignistag",
    "excludes zero": "schließt null aus",
    "includes zero": "enthält null",
    "CAR [0,+10] (market-adjusted)": "CAR [0,+10] (marktbereinigt)",
    "CAR [0,+10] (OLS market model)": "CAR [0,+10] (OLS-Marktmodell)",
    "50,000 resamples, deterministic seed. Intervals resample firms cross-sectionally and do not solve omitted-variable, dependence or event-confounding problems.": (
        "50.000 Wiederholungsstichproben mit deterministischem Startwert. Die "
        "Intervalle ziehen Unternehmen im Querschnitt neu und lösen weder Probleme "
        "ausgelassener Variablen noch Abhängigkeiten oder die Überlagerung von "
        "Ereignissen."
    ),
    "Long horizon: mixed performance": "Langer Horizont: gemischte Wertentwicklung",
    "Company return": "Unternehmensrendite",
    "Benchmark return": "Benchmark-Rendite",
    "Obs.": "Beob.",
    "Last date": "Letztes Datum",
    "Interpretation boundary.": "Interpretationsgrenze.",
    "A long-horizon return through 18 August absorbs many company-specific, sectoral, macroeconomic and policy events. Quartile shifts and BHAR are descriptive; they must not be presented as the effect of the 28 February event.": (
        "Eine langfristige Rendite bis zum 18. August nimmt zahlreiche "
        "unternehmensspezifische, sektorale, makroökonomische und politische "
        "Ereignisse auf. Quartilsverschiebungen und BHAR sind deskriptiv; sie dürfen "
        "nicht als Effekt des Ereignisses vom 28. Februar dargestellt werden."
    ),
    "Post-hoc mechanism checks": "Post-hoc-Prüfungen möglicher Mechanismen",
    "Show complete post-hoc comparison groups": (
        "Vollständige Post-hoc-Vergleichsgruppen anzeigen"
    ),
    "Post-hoc check": "Post-hoc-Prüfung",
    "Market window": "Marktfenster",
    "Group": "Gruppe",
    "Positive": "Positiv",
    "Positive every day": "An jedem Tag positiv",
    "Mean simple AR": "Mittlere einfache AR",
    "Median simple AR": "Mediane einfache AR",
    "Mean OLS AR": "Mittlere OLS-AR",
    "Pentagon production-acceleration report": (
        "Pentagon-Bericht zur Produktionsbeschleunigung"
    ),
    "Rheinmetall Skynex announcement and sector-wide July run": (
        "Rheinmetall-Skynex-Ankündigung und sektorweiter Juli-Anstieg"
    ),
    "Lockheed Martin": "Lockheed Martin",
    "Northrop Grumman": "Northrop Grumman",
    "General Dynamics": "General Dynamics",
    "Rtx": "RTX",
    "Us Defence Sp500": "US-Rüstung / S&P 500",
    "Us Non Defence Sp500": "US-Nichtrüstung / S&P 500",
    "All Defence": "Alle Rüstungsunternehmen",
    "All Non Defence": "Alle Nichtrüstungsunternehmen",
    "Defence Peers": "Rüstungs-Peers",
    "These checks were specified after inspecting later reports. They are retained because they test attractive narratives against complete comparison groups; they are explicitly post hoc and carry no confirmatory p-value.": (
        "Diese Prüfungen wurden nach Sichtung späterer Berichte festgelegt. Sie "
        "bleiben enthalten, weil sie attraktive Erzählungen anhand vollständiger "
        "Vergleichsgruppen testen; sie sind ausdrücklich post hoc und besitzen "
        "keinen konfirmatorischen p-Wert."
    ),
    # Energy and dependency.
    "Oil and consumer costs": "Öl und Verbraucherkosten",
    "Large co-movement, weak evidence of a delayed peak": (
        "Starke gemeinsame Bewegung, schwache Evidenz für ein verzögertes Maximum"
    ),
    "Indexed levels communicate scale but do not identify transmission. Weekly change correlations test lags 0–8. The star marker denotes a Spearman p-value below .05 after Holm correction within the nine-lag family for that product/tax series.": (
        "Indexierte Niveaus veranschaulichen die Größenordnung, identifizieren aber "
        "keine Übertragung. Korrelationen wöchentlicher Veränderungen prüfen "
        "Verzögerungen von 0 bis 8 Wochen. Der Stern markiert einen "
        "Spearman-p-Wert unter 0,05 nach Holm-Korrektur innerhalb der neun "
        "Verzögerungen der jeweiligen Produkt-/Steuerreihe."
    ),
    "Product": "Produkt",
    "Tax basis": "Steuerbasis",
    "Raw p": "Rohes p",
    "Spearman significant": "Spearman signifikant",
    "PETROL": "BENZIN",
    "DIESEL": "DIESEL",
    "WITH_TAX": "MIT_STEUERN",
    "WITHOUT_TAX": "OHNE_STEUERN",
    "yes": "ja",
    "no": "nein",
    "Before-tax correlations are stronger than tax-inclusive correlations, which is consistent with taxes dampening percentage movements in retail prices. This is an interpretation, not a causal estimate. EUR/USD movements, refining margins, inventories, regulation, demand and weekly autocorrelation remain uncontrolled.": (
        "Die Korrelationen vor Steuern sind stärker als die Korrelationen "
        "einschließlich Steuern. Dies ist damit vereinbar, dass Steuern prozentuale "
        "Bewegungen der Endverbraucherpreise dämpfen. Es handelt sich um eine "
        "Interpretation und nicht um eine kausale Schätzung. EUR/USD-Bewegungen, "
        "Raffineriemargen, Lagerbestände, Regulierung, Nachfrage und wöchentliche "
        "Autokorrelation bleiben unkontrolliert."
    ),
    "Economic dependency": "Wirtschaftliche Abhängigkeit",
    "Iran–China oil exposure is asymmetric": (
        "Die Öl-Exposition zwischen Iran und China ist asymmetrisch"
    ),
    "Sanctions, ship-to-ship transfers and indirect routes make customs records incomplete. All shares below are explicitly stored as estimates with denominator and reference period.": (
        "Sanktionen, Umladungen von Schiff zu Schiff und indirekte Routen machen "
        "Zollstatistiken unvollständig. Alle nachstehenden Anteile werden "
        "ausdrücklich als Schätzungen mit Nenner und Referenzzeitraum gespeichert."
    ),
    "Period": "Zeitraum",
    "China share": "China-Anteil",
    "China volume": "China-Volumen",
    "Share of China seaborne": "Anteil an Chinas Seeimporten",
    "Denominator": "Nenner",
    "Iran’s seller concentration is very high, but the reverse exposure is much smaller: Kpler’s 2025 estimate puts Iranian oil at 13.4% of China’s seaborne oil imports. “China buys 80–90%” therefore describes Iran’s export denominator, not China’s total oil demand.": (
        "Irans Verkäuferkonzentration ist sehr hoch, die umgekehrte Exposition "
        "jedoch deutlich geringer: Kplers Schätzung für 2025 beziffert iranisches "
        "Öl auf 13,4 % der chinesischen Rohölimporte auf dem Seeweg. „China kauft "
        "80–90 %“ beschreibt daher den Nenner der iranischen Exporte und nicht "
        "Chinas gesamte Ölnachfrage."
    ),
    "Arms-supply context": "Kontext der Waffenlieferungen",
    "Supplier": "Lieferland",
    "Recipient": "Empfängerland",
    "Share": "Anteil",
    "Scope": "Bezugsgröße",
    "SIPRI fact sheet": "SIPRI-Faktenblatt",
    # Ownership.
    "Institutional ownership layer": "Institutionelle Eigentumsebene",
    "BlackRock links issuer categories—but does not prove profit or influence": (
        "BlackRock verbindet Emittentenkategorien, belegt aber weder Gewinn noch Einfluss"
    ),
    "The company taxonomy classifies what issuers do; it does not imply that finance, defence and oil firms are ownership-independent. BlackRock’s official Q2 2026 Form 13F combination report verifies managed positions in four focal U.S. issuers. The table sums all filing rows sharing each CUSIP and deliberately omits ownership percentages, which require a separately matched shares-outstanding denominator.": (
        "Die Unternehmenstaxonomie klassifiziert die Tätigkeit der Emittenten; sie "
        "bedeutet nicht, dass Finanz-, Rüstungs- und Ölunternehmen eigentumsseitig "
        "unabhängig voneinander sind. BlackRocks offizieller kombinierter "
        "Form-13F-Bericht für Q2 2026 bestätigt verwaltete Positionen in vier "
        "untersuchten US-Emittenten. Die Tabelle summiert alle Meldungszeilen mit "
        "derselben CUSIP und verzichtet bewusst auf Eigentumsquoten, für die ein "
        "gesondert abgeglichener Nenner der ausstehenden Aktien erforderlich wäre."
    ),
    "Issuer": "Emittent",
    "Shares": "Aktien",
    "Filing value": "Meldewert",
    "Position date": "Positionsdatum",
    "Filed": "Eingereicht",
    "SEC filing": "SEC-Meldung",
    "The regulatory filing also states that BlackRock, Inc. is the parent of reporting investment managers and disclaims investment discretion over positions managed by those subsidiaries. The reported securities are therefore predominantly managed fund and client assets—not equivalent to BlackRock’s own balance-sheet investment, revenue or profit.": (
        "Die regulatorische Meldung erklärt außerdem, dass BlackRock, Inc. die "
        "Muttergesellschaft der meldenden Investmentmanager ist und für die von "
        "diesen Tochtergesellschaften verwalteten Positionen keine eigene "
        "Anlageentscheidung beansprucht. Die gemeldeten Wertpapiere sind daher "
        "überwiegend verwaltetes Fonds- und Kundenvermögen und nicht mit "
        "BlackRocks eigener Bilanzanlage, seinem Umsatz oder Gewinn gleichzusetzen."
    ),
    "BlackRock share-price comparator": "BlackRock als Aktienkurs-Vergleichswert",
    "What a real ownership study would require": (
        "Was eine belastbare Eigentumsstudie erfordern würde"
    ),
    "A defensible mark-to-market extension would use consecutive regulatory holdings snapshots, split-adjusted shares outstanding, security-level prices and explicit treatment of trading between quarter ends. Holding the 30 June share counts fixed over earlier dates would only be a hypothetical portfolio calculation—not BlackRock’s realised gain.": (
        "Eine belastbare Mark-to-Market-Erweiterung würde aufeinanderfolgende "
        "regulatorische Bestandsmeldungen, splitbereinigte ausstehende Aktien, "
        "wertpapierspezifische Preise und eine ausdrückliche Behandlung der "
        "Transaktionen zwischen Quartalsenden verwenden. Die Aktienzahlen vom "
        "30. Juni für frühere Zeitpunkte konstant zu halten, wäre lediglich eine "
        "hypothetische Portfoliorechnung und nicht BlackRocks realisierter Gewinn."
    ),
    # Operational evidence.
    "Official operational record": "Offizieller Operationsnachweis",
    "CENTCOM series retained; ACLED 2026 removed": (
        "CENTCOM-Reihe beibehalten; ACLED 2026 entfernt"
    ),
    "Patriot replenishment: a documented mechanism, not an equity effect": (
        "Patriot-Nachbeschaffung: dokumentierter Mechanismus, kein Aktieneffekt"
    ),
    "Date": "Datum",
    "Type": "Typ",
    "Estimate / signal": "Schätzung / Signal",
    "Company relevance": "Unternehmensrelevanz",
    "Evidence": "Evidenz",
    "qualitative": "qualitativ",
    "The retained operational series counts release-confirmed days, not individual strikes, targets or fatalities. Multiple targets on one day still equal one operation day. It is suitable for documenting U.S. self-reported activity, not for measuring total conflict intensity.": (
        "Die beibehaltene Operationsreihe zählt durch Mitteilungen bestätigte Tage "
        "und nicht einzelne Angriffe, Ziele oder Todesopfer. Mehrere Ziele an einem "
        "Tag ergeben weiterhin nur einen Operationstag. Die Reihe eignet sich zur "
        "Dokumentation selbst gemeldeter US-Aktivitäten, nicht zur Messung der "
        "gesamten Konfliktintensität."
    ),
    "Show all 23 core operation days": "Alle 23 Kern-Operationstage anzeigen",
    "Title": "Originaltitel",
    "Counting unit": "Zähleinheit",
    "other": "sonstige",
    "airstrike": "Luftangriff",
    "official_release_confirmed_operation_day": (
        "durch_offizielle_mitteilung_bestätigter_operationstag"
    ),
    "release": "Mitteilung",
    "Exploratory procurement check": "Explorative Prüfung von Beschaffungsmeldungen",
    "Announcement": "Ankündigung",
    "OLS status": "OLS-Status",
    "announcement": "Ankündigung",
    "insufficient_estimation_window": "unzureichendes_schätzfenster",
    "ok": "ok",
    # Methods.
    "Implementation": "Implementierung",
    "Reproducible object-oriented Python framework": (
        "Reproduzierbares objektorientiertes Python-Framework"
    ),
    "Object model and analysis": "Objektmodell und Analyse",
    "is specialized into": "wird spezialisiert in",
    "and": "und",
    "into role, price and impact observations. Abstract source adapters support RSS, HTML, GDELT, broadcast CSV and USAspending inputs. Service classes isolate OLS, event-study, lag, validation and robustness logic.": (
        "in Rollen-, Preis- und Wirkungsbeobachtungen. Abstrakte Quellenadapter "
        "unterstützen RSS, HTML, GDELT, Broadcast-CSV und USAspending-Eingaben. "
        "Serviceklassen kapseln OLS-, Ereignisstudien-, Verzögerungs-, "
        "Validierungs- und Robustheitslogik."
    ),
    "Persistence and validation": "Persistenz und Validierung",
    "to SQLite. Every stored row retains reporting period, unit, source, status and its original JSON payload. CSV imports are checksum-tracked, transactional and idempotent. Automated tests cover models, adapters, methods and exports.": (
        "auf SQLite ab. Jede gespeicherte Zeile behält Berichtszeitraum, Einheit, "
        "Quelle, Status und die ursprüngliche JSON-Nutzlast. CSV-Importe werden "
        "über Prüfsummen verfolgt, transaktional ausgeführt und sind idempotent. "
        "Automatisierte Tests decken Modelle, Adapter, Methoden und Exporte ab."
    ),
    "Rebuild commands": "Befehle zur Reproduktion",
    "The Rheinmetall procurement command takes four explicit file paths; the complete invocation is documented in": (
        "Der Rheinmetall-Beschaffungsbefehl benötigt vier explizite Dateipfade; "
        "der vollständige Aufruf ist dokumentiert in"
    ),
    "Core source links": "Zentrale Quellenlinks",
    "UCDP — datasets, versions and codebooks": "UCDP — Datensätze, Versionen und Codebücher",
    "UCDP — conflict and actor definitions": "UCDP — Konflikt- und Akteursdefinitionen",
    "U.S. EIA — daily Brent prices": "U.S. EIA — tägliche Brent-Preise",
    "U.S. EIA — Iran country analysis": "U.S. EIA — Länderanalyse Iran",
    "Reuters/Kpler — China’s Iranian-oil purchases": (
        "Reuters/Kpler — Chinas Käufe iranischen Öls"
    ),
    "SIPRI — Trends in International Arms Transfers 2025": (
        "SIPRI — Trends internationaler Waffentransfers 2025"
    ),
    "SEC — BlackRock Q2 2026 Form 13F": "SEC — BlackRock Form 13F, Q2 2026",
    "CSIS — interceptor inventory estimate": "CSIS — Schätzung des Abfangraketenbestands",
    "Associated Press — production-acceleration report": (
        "Associated Press — Bericht zur Produktionsbeschleunigung"
    ),
    "CENTCOM — Operation Epic Fury launch release": (
        "CENTCOM — Startmitteilung zu Operation Epic Fury"
    ),
    "German Federal Government — position of 1 March 2026": (
        "Bundesregierung — Position vom 1. März 2026"
    ),
    "Chinese Foreign Ministry — statement of 28 February 2026": (
        "Chinesisches Außenministerium — Stellungnahme vom 28. Februar 2026"
    ),
    # Open questions.
    "What we still cannot answer": "Was wir weiterhin nicht beantworten können",
    "Open economic questions the data raises but cannot settle": (
        "Offene wirtschaftliche Fragen, die aus den Daten entstehen, aber nicht beantwortet werden können"
    ),
    "These are research questions generated by the evidence and its limitations. They are deliberately separated from the empirical findings and must not be read as claims that the present dataset confirms.": (
        "Diese Forschungsfragen ergeben sich aus der Evidenz und ihren Grenzen. "
        "Sie sind bewusst von den empirischen Ergebnissen getrennt und dürfen "
        "nicht als Aussagen verstanden werden, die der vorliegende Datensatz "
        "bestätigt."
    ),
    "Israel → Germany: how exposed is German industry?": (
        "Israel → Deutschland: Wie stark ist die deutsche Industrie exponiert?"
    ),
    "Israeli escalation rhetoric and German economic reactions run as two separate evidence threads in this project, connected only indirectly through the oil-price channel. Whether German industry has meaningful direct exposure to Israeli technology supply chains—such as semiconductor design, cybersecurity or defence electronics—that a specific Israeli escalation step could disrupt is not something this dataset can show. It would require a company-level Israel-revenue and supplier-exposure panel plus an event study anchored specifically on verified Israeli decision dates rather than U.S. or Iranian dates.": (
        "Israelische Eskalationsrhetorik und deutsche Wirtschaftsreaktionen bilden "
        "in diesem Projekt zwei getrennte Evidenzstränge, die nur indirekt über den "
        "Ölpreiskanal verbunden sind. Ob die deutsche Industrie eine relevante "
        "direkte Exposition gegenüber israelischen Technologie-Lieferketten besitzt "
        "– etwa bei Halbleiterdesign, Cybersicherheit oder Rüstungselektronik –, die "
        "durch einen konkreten israelischen Eskalationsschritt gestört werden "
        "könnte, lässt sich mit diesem Datensatz nicht zeigen. Dafür wären ein "
        "Unternehmenspanel zu Israel-Umsätzen und Lieferantenexpositionen sowie eine "
        "Ereignisstudie erforderlich, die gezielt auf verifizierten israelischen "
        "Entscheidungsterminen und nicht auf US-amerikanischen oder iranischen "
        "Terminen basiert."
    ),
    "What is really driving Germany's higher borrowing costs?": (
        "Was treibt Deutschlands höhere Finanzierungskosten tatsächlich?"
    ),
    "Selected political commentary attributes movements in German Bund yields to the war, but the same period also contains global inflation pressure, energy-price shocks with multiple causes and anticipation of German defence and infrastructure borrowing. Without continuous official yield series and controls such as U.S. Treasuries and comparable euro-area sovereign bonds, that attribution remains one plausible narrative among several—not a causal estimate.": (
        "Ausgewählte politische Kommentare führen Bewegungen der Renditen deutscher "
        "Bundesanleihen auf den Krieg zurück. Im selben Zeitraum wirkten jedoch auch "
        "globaler Inflationsdruck, Energiepreisschocks mit mehreren Ursachen und die "
        "Erwartung zusätzlicher deutscher Kreditaufnahme für Verteidigung und "
        "Infrastruktur. Ohne durchgängige offizielle Renditezeitreihen und "
        "Kontrollgrößen wie US-Staatsanleihen und vergleichbare Staatsanleihen des "
        "Euroraums bleibt diese Zuschreibung eine von mehreren plausiblen "
        "Erzählungen und keine kausale Schätzung."
    ),
    "How much \"war profit\" actually stays in Germany?": (
        "Wie viel „Kriegsgewinn“ verbleibt tatsächlich in Deutschland?"
    ),
    "Several Rheinmetall contracts in the curated announcement sample involve third-country customers. Headline contract value does not reveal where production, employment, taxation and value added occur. A foreign or licensed production line can carry the same order value while creating a very different German economic footprint. The current project contains no production-location or domestic-value-added dataset.": (
        "Mehrere Rheinmetall-Verträge in der kuratierten Ankündigungsstichprobe "
        "betreffen Kunden in Drittländern. Der ausgewiesene Auftragswert zeigt "
        "nicht, wo Produktion, Beschäftigung, Besteuerung und Wertschöpfung "
        "stattfinden. Eine ausländische oder lizenzierte Produktionslinie kann "
        "denselben Auftragswert aufweisen und dennoch einen völlig anderen "
        "wirtschaftlichen Fußabdruck in Deutschland erzeugen. Das aktuelle Projekt "
        "enthält keinen Datensatz zu Produktionsstandorten oder inländischen "
        "Wertschöpfungsanteilen."
    ),
    "Does BlackRock's dual exposure create a voting conflict?": (
        "Erzeugt BlackRocks doppelte Exposition einen Abstimmungskonflikt?"
    ),
    "The verified filing shows BlackRock-managed positions across defence and oil issuers, but it does not show how BlackRock votes, whether mandates differ across funds or whether voting changes with issuer-level conflict exposure. Answering that question would require longitudinal proxy-voting records, mandate-level ownership data and a pre-specified comparison design. It is a legitimate governance question raised by the ownership layer—not a conflict that this project can support or refute.": (
        "Die verifizierte Meldung zeigt von BlackRock verwaltete Positionen in "
        "Rüstungs- und Ölemittenten. Sie zeigt jedoch nicht, wie BlackRock abstimmt, "
        "ob sich die Mandate zwischen Fonds unterscheiden oder ob sich das "
        "Abstimmungsverhalten mit der Konfliktexposition einzelner Emittenten "
        "verändert. Zur Beantwortung wären longitudinale Daten zu "
        "Stimmrechtsausübungen, Eigentumsdaten auf Mandatsebene und ein vorab "
        "festgelegtes Vergleichsdesign erforderlich. Es handelt sich um eine "
        "legitime Governance-Frage, die sich aus der Eigentumsebene ergibt, nicht "
        "um einen Konflikt, den dieses Projekt bestätigen oder widerlegen kann."
    ),
    # Audit and appendix.
    "Scope control": "Kontrolle des Untersuchungsumfangs",
    "What is included—and deliberately excluded": (
        "Was einbezogen und bewusst ausgeschlossen wird"
    ),
    "Module": "Modul",
    "Decision": "Entscheidung",
    "Reason": "Begründung",
    "Claim-by-claim audit of the supplied additional findings": (
        "Einzelprüfung der zusätzlich bereitgestellten Befunde"
    ),
    "Show the complete additional-findings audit": (
        "Vollständige Prüfung der Zusatzbefunde anzeigen"
    ),
    "Topic": "Thema",
    "Supported conclusion": "Gestützte Schlussfolgerung",
    "Not supported": "Nicht gestützt",
    "SQLite data register": "SQLite-Datenregister",
    "Dataset": "Datensatz",
    "CSV path": "CSV-Pfad",
    "Rows": "Zeilen",
    "Unit": "Einheit",
    "Default status": "Standardstatus",
    "Approved own-project data route.": "Genehmigter Weg mit eigenem Projekt.",
    "The professor confirmed that students using their own project do not need to implement the separate faculty-supplied train/ideal/test task. This submission therefore documents the purpose, structure and provenance of its self-collected company, market, energy and country-context data and provides the corresponding tested Python implementation.": (
        "Der Professor hat bestätigt, dass Studierende mit einem eigenen Projekt "
        "die separate, vom Lehrstuhl bereitgestellte Trainings-/Ideal-/Testaufgabe "
        "nicht umsetzen müssen. Diese Abgabe dokumentiert daher Zweck, Struktur und "
        "Herkunft der selbst erhobenen Unternehmens-, Markt-, Energie- und "
        "Länderkontextdaten und enthält die zugehörige getestete Python-Implementierung."
    ),
    "BLACK DOVES written-assignment edition · Descriptive association study · Core period fixed at 2026-01-01 to 2026-08-18 · This report is self-contained and renders its Bokeh charts offline.": (
        "BLACK DOVES – Abgabeversion der schriftlichen Ausarbeitung · Deskriptive "
        "Assoziationsstudie · Kernzeitraum festgelegt auf 01.01.2026 bis "
        "18.08.2026 · Dieser Bericht ist eigenständig und stellt seine "
        "Bokeh-Diagramme offline dar."
    ),
}


# Exact dataset descriptions that are part of the report rather than original
# source titles.  Status codes stay in their machine-readable original form.
TRANSLATIONS.update(
    {
        "Conceptual framework": "Konzeptioneller Rahmen",
        "UCDP Definitions": "UCDP-Definitionen",
        "accessed 2026-09-14": "abgerufen am 14.09.2026",
        "Define actor armed conflict and secondary-party categories": (
            "Definition der Kategorien Akteur, bewaffneter Konflikt und Sekundärpartei"
        ),
        "Definitions guide terminology but do not by themselves classify the focal 2026 event": (
            "Die Definitionen leiten die Terminologie, klassifizieren das Fokusereignis 2026 aber nicht eigenständig"
        ),
        "Historical conflict-year reference": "Historische Referenz nach Konfliktjahren",
        "The annual release ends in 2025 and therefore cannot code the focal 2026 period": (
            "Die jährliche Veröffentlichung endet 2025 und kann den Fokuszeitraum 2026 daher nicht kodieren"
        ),
        "Actors represented in UCDP version 26.1": "In UCDP-Version 26.1 erfasste Akteure",
        "Historical actor names conflicts dyads origins and alliances": (
            "Historische Akteursnamen, Konflikte, Dyaden, Ursprünge und Allianzen"
        ),
        "No row-level UCDP extract was present in the supplied project and no UCDP actor observations enter the statistical results": (
            "Im bereitgestellten Projekt lag kein UCDP-Auszug auf Zeilenebene vor; keine UCDP-Akteursbeobachtung geht in die statistischen Ergebnisse ein"
        ),
        "United States": "Vereinigte Staaten",
        "Germany": "Deutschland",
        "Russia": "Russland",
        "Largest supplier to Israel in 2021-2025: 68% of Israeli major-arms imports": (
            "Größter Lieferant Israels 2021–2025: 68 % der israelischen Großwaffenimporte"
        ),
        "Direct participant; CENTCOM states U.S. and partner forces launched Operation Epic Fury": (
            "Direkter Teilnehmer; laut CENTCOM starteten US- und Partnerkräfte die Operation Epic Fury"
        ),
        "Oil-price and defence-sector exposure": "Exposition gegenüber Ölpreisen und dem Rüstungssektor",
        "Recipient: United States 68% and Germany 31% of major-arms imports in 2021-2025": (
            "Empfänger: Vereinigte Staaten 68 % und Deutschland 31 % der Großwaffenimporte 2021–2025"
        ),
        "Direct participant in campaign against Iran": "Direkter Teilnehmer an der Kampagne gegen Iran",
        "Defence-sector and energy-price exposure": "Exposition gegenüber Rüstungssektor und Energiepreisen",
        "Recipient: Russia was the only recorded supplier of major arms in 2021-2025; Iran represented 0.2% of Middle East imports": (
            "Empfänger: Russland war 2021–2025 der einzige erfasste Großwaffenlieferant; Iran entfiel auf 0,2 % der Importe des Nahen Ostens"
        ),
        "Direct participant and source of counterstrikes described by official third-country statements": (
            "Direkter Teilnehmer und Urheber von Gegenschlägen laut offiziellen Stellungnahmen von Drittstaaten"
        ),
        "High dependence on crude-oil export revenue and concentrated sales to China": (
            "Hohe Abhängigkeit von Rohölexporterlösen und konzentrierter Absatz an China"
        ),
        "Second-largest supplier to Israel in 2021-2025: 31% of Israeli major-arms imports": (
            "Zweitgrößter Lieferant Israels 2021–2025: 31 % der israelischen Großwaffenimporte"
        ),
        "Politically aligned with several stated U.S./Israeli goals while expressing reservations and escalation risk; no direct participation coded": (
            "Politische Übereinstimmung mit mehreren erklärten US-amerikanischen/israelischen Zielen bei gleichzeitigen Vorbehalten und Hinweisen auf Eskalationsrisiken; keine direkte Beteiligung kodiert"
        ),
        "Consumer exposure through Brent-to-petrol/diesel transmission": (
            "Verbraucherexposition über die Übertragung von Brent auf Benzin und Diesel"
        ),
        "No China-to-Iran transfer is inferred from the selected SIPRI 2021-2025 evidence": (
            "Aus der ausgewählten SIPRI-Evidenz 2021–2025 wird kein Transfer von China an Iran abgeleitet"
        ),
        "Called for an immediate stop to military action and a return to dialogue": (
            "Forderte die sofortige Einstellung militärischer Handlungen und die Rückkehr zum Dialog"
        ),
        "Purchased more than 80% of Iran's shipped oil in the 2025 Kpler estimate; concentrated buyer for Iran but Iranian oil was 13.4% of China's seaborne imports": (
            "Kaufte laut Kpler-Schätzung 2025 mehr als 80 % des verschifften iranischen Öls; konzentrierter Käufer für Iran, während iranisches Öl 13,4 % der chinesischen Seeimporte ausmachte"
        ),
        "Share of Iran crude-oil and condensate exports ultimately destined for China": (
            "Anteil der iranischen Rohöl- und Kondensatexporte mit endgültigem Bestimmungsziel China"
        ),
        "Share of Iran's shipped oil bought by China; comparison share is Iranian oil in China's seaborne oil imports": (
            "Anteil des verschifften iranischen Öls, das China kaufte; Vergleichsanteil: iranisches Öl an Chinas Rohölimporten auf dem Seeweg"
        ),
        "Share of Iran oil exports purchased by China": "Anteil der von China gekauften iranischen Ölexporte",
        "Share of Israel's imports of major arms": "Anteil an Israels Importen von Großwaffen",
        "Share of Iran's recorded imports of major arms by supplier": (
            "Anteil an Irans erfassten Großwaffenimporten nach Lieferland"
        ),
        "CSIS estimated that the U.S. inventory had fallen below 1,000 and placed the current range at 759-827 from a pre-war baseline of 2,330.": (
            "CSIS schätzte, dass der US-Bestand von einem Vorkriegswert von 2.330 auf unter 1.000 und aktuell auf 759–827 gesunken war."
        ),
        "CSIS estimated a decline of at least 65 percent in Patriot interceptors from the pre-war baseline.": (
            "CSIS schätzte einen Rückgang der Patriot-Abfangraketen um mindestens 65 % gegenüber dem Vorkriegswert."
        ),
        "U.S. defence industry": "US-Rüstungsindustrie",
        "AP reported that the Pentagon confirmed efforts to accelerate production and delivery of critical weapons; the Pentagon also said the wider modernization effort predated the conflict.": (
            "AP berichtete, das Pentagon habe Bemühungen zur beschleunigten Produktion und Auslieferung kritischer Waffen bestätigt; laut Pentagon begann das umfassendere Modernisierungsvorhaben bereits vor dem Konflikt."
        ),
        "RTX identifies Raytheon as supplier of Patriot PAC-2 GEM-T interceptors.": (
            "RTX nennt Raytheon als Lieferanten der Patriot-PAC-2-GEM-T-Abfangraketen."
        ),
        "The U.S. Army identifies Lockheed Martin's PAC-3 MSE as an interceptor employed within the Patriot weapon system.": (
            "Die U.S. Army nennt Lockheed Martins PAC-3 MSE als eine im Patriot-Waffensystem eingesetzte Abfangrakete."
        ),
        "759–827 interceptors": "759–827 Abfangraketen",
        "≥65 percent": "≥65 Prozent",
        "Five curated Rheinmetall air-defence announcements yield a mean market-adjusted CAR [0,+10] of -2.52%. Four have a valid OLS estimate; their mean OLS CAR is -7.91%. Both aggregate means are negative, so the small series does not support a general positive procurement-announcement effect. The Italian record is dated 15 January": (
            "Fünf kuratierte Rheinmetall-Ankündigungen zur Luftverteidigung ergeben einen mittleren marktbereinigten CAR [0,+10] von -2,52 %. Für vier liegt eine gültige OLS-Schätzung vor; ihr mittlerer OLS-CAR beträgt -7,91 %. Beide aggregierten Mittelwerte sind negativ. Die kleine Reihe stützt daher keinen allgemeinen positiven Effekt von Beschaffungsankündigungen. Der italienische Eintrag ist auf den 15. Januar"
        ),
        "and concerns": "und betrifft",
        ", not Skyranger: event-day abnormal return was −1.28%, followed by +4.12% on day +1. Irregular signs and lags are realistic, but they are not a provenance test.": (
            ", nicht Skyranger: Die abnormale Rendite am Ereignistag betrug −1,28 %, gefolgt von +4,12 % an Tag +1. Unregelmäßige Vorzeichen und Verzögerungen sind realistisch, aber kein Provenienztest."
        ),
        "Italy orders first Skynex air defence system": "Italien bestellt erstes Skynex-Luftverteidigungssystem",
        "Leopard 1 Skyranger 35 order for Ukraine": "Auftrag über Leopard 1 Skyranger 35 für die Ukraine",
        "Netherlands orders Skyranger 30 systems": "Niederlande bestellen Skyranger-30-Systeme",
        "Romania awards multi-domain defence package including air defence": (
            "Rumänien vergibt domänenübergreifendes Verteidigungspaket einschließlich Luftverteidigung"
        ),
        "Four Skynex systems ordered by international customer": (
            "Internationaler Kunde bestellt vier Skynex-Systeme"
        ),
        "UCDP definitions and historical catalogues": "UCDP-Definitionen und historische Kataloge",
        "Used to define concepts and document available historical resources; no UCDP row is treated as a 2026 statistical observation.": (
            "Dient der Begriffsdefinition und Dokumentation verfügbarer historischer Ressourcen; keine UCDP-Zeile wird als statistische Beobachtung für 2026 behandelt."
        ),
        "2026 ACLED aggregate": "ACLED-Aggregat 2026",
        "Access is available only through 2025; the supplied 2026 aggregate cannot be verified and is not conflict-specific.": (
            "Der Zugriff reicht nur bis 2025; das bereitgestellte Aggregat für 2026 kann nicht verifiziert werden und ist nicht konfliktspezifisch."
        ),
        "Media-positioning pilot": "Pilot zur Medienpositionierung",
        "Zero manually reviewed documents. RND supplies 178/247 records (72.1% of all records; 86.4% of the NEWS layer), so country-intensity comparisons would reproduce collection bias.": (
            "Kein Dokument wurde manuell geprüft. RND liefert 178 von 247 Datensätzen (72,1 % aller Datensätze; 86,4 % der NEWS-Ebene), sodass Vergleiche der Länderintensität die Erhebungsverzerrung reproduzieren würden."
        ),
        "Casualty/damage compilation": "Zusammenstellung von Opfer- und Schadenszahlen",
        "Self, NGO, UN and adversary numbers have incompatible denominators and dates and were supplied through one secondary compilation. The discrepancy is a source-criticism result, not an intensity variable.": (
            "Eigenangaben sowie Zahlen von NGO, UN und Gegnern besitzen inkompatible Nenner und Stichtage und wurden über eine einzige Sekundärzusammenstellung geliefert. Die Diskrepanz ist ein Ergebnis der Quellenkritik und keine Intensitätsvariable."
        ),
        "German DAX/Bund anchors": "Deutsche DAX-/Bund-Ankerpunkte",
        "Sparse selected news points mix closes, intraday levels and approximations; several fall after 18 August. A continuous official series and controls are required.": (
            "Wenige ausgewählte Meldungspunkte vermischen Schlusskurse, Intraday-Niveaus und Näherungswerte; mehrere liegen nach dem 18. August. Erforderlich sind eine durchgängige offizielle Reihe und Kontrollgrößen."
        ),
        "Direct Israel–Germany effect": "Direkter Israel–Deutschland-Effekt",
        "No pre-specified Israeli decision series is linked to German target assets. This is a documented research gap.": (
            "Keine vorab festgelegte Reihe israelischer Entscheidungen ist mit deutschen Zielwerten verknüpft. Dies ist eine dokumentierte Forschungslücke."
        ),
        "Company-announcement universe": "Universum der Unternehmensankündigungen",
        "Only five human-reviewed Rheinmetall records; inadequate coverage for 46-company comparison.": (
            "Nur fünf manuell geprüfte Rheinmetall-Datensätze; unzureichende Abdeckung für einen Vergleich von 46 Unternehmen."
        ),
        "CENTCOM operation days": "CENTCOM-Operationstage",
        "Official self-report, retained separately and never treated as total conflict intensity.": (
            "Offizielle Selbstauskunft, getrennt beibehalten und nicht als gesamte Konfliktintensität behandelt."
        ),
        "Market and energy results": "Markt- und Energieergebnisse",
        "Reproducible calculations with explicit provenance and limitations.": (
            "Reproduzierbare Berechnungen mit expliziter Provenienz und Einschränkungen."
        ),
        "Casualty estimates": "Opferschätzungen",
        "The mismatch demonstrates denominator, timing and source-verification risk.": (
            "Die Abweichung zeigt Risiken bei Nenner, Zeitpunkt und Quellenverifikation."
        ),
        "Do not infer the true toll, the direction of each party's bias, intent to misreport, or a conflict-intensity series.": (
            "Weder die tatsächliche Opferzahl noch Richtung oder Absicht einer Verzerrung oder eine Konfliktintensitätsreihe dürfen daraus abgeleitet werden."
        ),
        "OLS beta pattern": "OLS-Beta-Muster",
        "The firms differ substantially in historical broad-market loading; low R2 for the three traditional primes makes single-benchmark estimates model-sensitive.": (
            "Die Unternehmen unterscheiden sich deutlich in ihrer historischen Belastung durch den Gesamtmarkt; niedrige R²-Werte der drei traditionellen Hauptauftragnehmer machen Ein-Benchmark-Schätzungen modellsensitiv."
        ),
        "Do not interpret beta as conflict sensitivity or low beta as proof of a conflict-specific return.": (
            "Beta darf weder als Konfliktsensitivität noch ein niedriges Beta als Beweis für eine konfliktspezifische Rendite interpretiert werden."
        ),
        "Patriot replenishment": "Patriot-Nachbeschaffung",
        "There is a documented replenishment and production-capacity channel relevant to both RTX and Lockheed Martin.": (
            "Ein dokumentierter Nachbeschaffungs- und Produktionskapazitätskanal ist für RTX und Lockheed Martin relevant."
        ),
        "Do not call the inventory estimate official, count repeated reports as independent estimates, assign all Patriot demand to RTX, or infer a causal equity effect.": (
            "Die Bestandsschätzung darf nicht als offiziell bezeichnet, wiederholte Berichte dürfen nicht als unabhängige Schätzungen gezählt, die gesamte Patriot-Nachfrage darf nicht RTX zugerechnet und kein kausaler Aktieneffekt abgeleitet werden."
        ),
        "German DAX and Bund channels": "Deutsche DAX- und Bund-Kanäle",
        "Equity-index and sovereign-yield channels are plausible extensions requiring continuous official series and controls.": (
            "Aktienindex- und Staatsanleiherenditekanäle sind plausible Erweiterungen, erfordern jedoch durchgängige offizielle Reihen und Kontrollgrößen."
        ),
        "Do not estimate a German channel or attribute selected DAX/Bund observations to the conflict.": (
            "Ein deutscher Kanal darf nicht geschätzt und ausgewählte DAX-/Bund-Beobachtungen dürfen nicht dem Konflikt zugeschrieben werden."
        ),
        "Pentagon casualty recategorization": "Neukategorisierung von Pentagon-Opferzahlen",
        "Changing definitions would create a structural break if independently documented.": (
            "Veränderte Definitionen würden bei unabhängiger Dokumentation einen Strukturbruch erzeugen."
        ),
        "Do not state that figures were manipulated or use the pilot summaries as a time-consistent escalation proxy.": (
            "Es darf weder behauptet werden, Zahlen seien manipuliert worden, noch dürfen die Pilotzusammenfassungen als zeitkonsistenter Eskalationsindikator dienen."
        ),
        "Media source imbalance": "Ungleichgewicht der Medienquellen",
        "The corpus is unsuitable for cross-country media-intensity comparisons and the concentration itself is a sampling audit result.": (
            "Der Korpus ist für länderübergreifende Vergleiche der Medienintensität ungeeignet; die Konzentration selbst ist ein Ergebnis der Stichprobenprüfung."
        ),
        "Do not infer that German coverage objectively dominated or use auto-suggested classifications as validated evidence.": (
            "Es darf weder eine objektive Dominanz deutscher Berichterstattung abgeleitet noch eine automatisch vorgeschlagene Klassifikation als validierte Evidenz verwendet werden."
        ),
        "Rheinmetall July two-day run": "Zweitägiger Rheinmetall-Anstieg im Juli",
        "The movement was sector-wide; a firm-specific component remains possible but is not isolated.": (
            "Die Bewegung war sektorweit; ein unternehmensspezifischer Anteil bleibt möglich, ist aber nicht isoliert."
        ),
        "Do not attribute the two-day run solely to the Skynex announcement or to a selected political speech without a separately identified event design.": (
            "Der zweitägige Anstieg darf ohne gesondert identifiziertes Ereignisdesign weder allein der Skynex-Ankündigung noch einer ausgewählten politischen Rede zugeschrieben werden."
        ),
        "Pentagon production report market anchor": "Marktanker des Pentagon-Produktionsberichts",
        "The Sunday-to-Monday timing is plausible and the four U.S. primes moved together, but the result is not sector-specific in this panel.": (
            "Die zeitliche Abfolge von Sonntag auf Montag ist plausibel und die vier US-Hauptauftragnehmer bewegten sich gemeinsam; das Ergebnis ist in diesem Panel jedoch nicht sektorspezifisch."
        ),
        "Do not describe two selected companies as independent causal confirmation or claim a direct media-to-price effect.": (
            "Zwei ausgewählte Unternehmen dürfen weder als unabhängige kausale Bestätigung beschrieben noch darf ein direkter Medien-zu-Kurs-Effekt behauptet werden."
        ),
        "BlackRock ownership network": "BlackRock-Eigentumsnetzwerk",
        "Issuer-sector categories do not represent an ownership network; common institutional holdings are a distinct descriptive layer.": (
            "Emittenten-Sektorkategorien bilden kein Eigentumsnetzwerk ab; gemeinsame institutionelle Positionen sind eine eigene deskriptive Ebene."
        ),
        "Do not treat customer fund assets as BlackRock's own balance-sheet gain, infer voting influence, or claim ownership percentages without matched shares-outstanding data.": (
            "Kunden- und Fondsvermögen darf nicht als BlackRocks eigener Bilanzgewinn behandelt, Stimmrechtseinfluss darf nicht abgeleitet und Eigentumsquoten dürfen ohne abgeglichene Daten zu ausstehenden Aktien nicht behauptet werden."
        ),
        "Israel-to-Germany direct channel": "Direkter Israel–Deutschland-Kanal",
        "A direct bilateral channel is not identified by the current design and requires a separate event study.": (
            "Ein direkter bilateraler Kanal wird durch das aktuelle Design nicht identifiziert und erfordert eine eigene Ereignisstudie."
        ),
        "Do not infer a direct Israel-to-Germany effect from parallel narrative and German price series.": (
            "Aus parallelen Erzählsträngen und deutschen Preisreihen darf kein direkter Israel–Deutschland-Effekt abgeleitet werden."
        ),
        "Post-cutoff media and market coverage": "Medien- und Marktabdeckung nach dem Stichtag",
        "Later records may motivate a future, newly specified extension.": (
            "Spätere Datensätze können eine künftig neu spezifizierte Erweiterung begründen."
        ),
        "Do not move the endpoint after inspecting dramatic later stories or mix post-cutoff context into the fixed-window estimands.": (
            "Der Endpunkt darf nach Sichtung späterer dramatischer Meldungen nicht verschoben und Kontext nach dem Stichtag darf nicht mit den Schätzgrößen des festen Fensters vermischt werden."
        ),
        "Audited 2026-09-14": "Geprüft am 14.09.2026",
        "claim-level inclusion decision": "Einbeziehungsentscheidung auf Aussagenebene",
        "percent of major-arms import volume": "Prozent des Importvolumens von Großwaffen",
        "shares and U.S. dollars": "Aktien und US-Dollar",
        "official release-confirmed operation day": "durch offizielle Mitteilung bestätigter Operationstag",
        "qualitative multidimensional classification": "qualitative mehrdimensionale Klassifikation",
        "row-specific": "zeilenspezifisch",
        "mixed; see column names": "gemischt; siehe Spaltennamen",
        "decimal return": "Dezimalrendite",
        "correlation coefficient and p-value": "Korrelationskoeffizient und p-Wert",
        "percent; million barrels/day": "Prozent; Millionen Barrel/Tag",
        "document count and percent": "Dokumentenzahl und Prozent",
        "row-specific estimate or qualitative signal": "zeilenspezifische Schätzung oder qualitatives Signal",
        "methodological source register": "methodisches Quellenregister",
        "SQLAlchemy maps": "SQLAlchemy bildet",
        "European Commission — Weekly Oil Bulletin": (
            "Europäische Kommission — Wöchentliches Ölbulletin"
        ),
        "2026-07-01 to 2026-07-02": "01.07.2026 bis 02.07.2026",
        "Position date 2026-06-30; filed 2026-08-07": (
            "Positionsdatum 30.06.2026; eingereicht am 07.08.2026"
        ),
        "Event 2026-02-28; market window [0,+10]": (
            "Ereignis 28.02.2026; Marktfenster [0,+10]"
        ),
        "2026 pilot; audited 2026-09-14": (
            "Pilot 2026; geprüft am 14.09.2026"
        ),
        "Definitions accessed 2026-09-14; annual data through 2025": (
            "Definitionen abgerufen am 14.09.2026; Jahresdaten bis 2025"
        ),
    }
)


REGEX_TRANSLATIONS = [
    (
        re.compile(r"Reproducible Python analysis · generated (\d{4}-\d{2}-\d{2})"),
        r"Reproduzierbare Python-Analyse · erstellt am \1",
    ),
    (
        re.compile(r"Confirmatory n=8; 95% percentile-bootstrap interval (.+)\."),
        r"Konfirmatorisch n=8; 95%-Perzentil-Bootstrap-Intervall \1.",
    ),
    (
        re.compile(r"Market-adjusted mean; 95% interval (.+)\."),
        r"Marktbereinigter Mittelwert; 95%-Intervall \1.",
    ),
    (
        re.compile(r"Confirmatory minus exploratory CAR; interval (.+) includes zero\."),
        r"Konfirmatorischer minus explorativer CAR; das Intervall \1 enthält null.",
    ),
    (
        re.compile(r"Mean through 18 Aug; (\d+)/8 companies positive\. Long-run performance is mixed\."),
        r"Mittelwert bis 18. Aug.; \1/8 Unternehmen positiv. Die langfristige Wertentwicklung ist gemischt.",
    ),
    (
        re.compile(r"Across the aligned weekly endpoints, Brent rose (.+), German petrol including tax (.+), and diesel including tax (.+)\. The strongest rank correlations occur contemporaneously at lag 0\. After Holm correction, (\d+)/4 lag-0 series remain significant—both before-tax series; delayed lags 1–8 do not provide a robust transmission peak\."),
        r"Über die abgestimmten wöchentlichen Endpunkte stieg Brent um \1, deutsches Benzin einschließlich Steuern um \2 und Diesel einschließlich Steuern um \3. Die stärksten Rangkorrelationen treten gleichzeitig bei Verzögerung 0 auf. Nach Holm-Korrektur bleiben \4/4 Reihen bei Verzögerung 0 signifikant – beide Reihen vor Steuern; die Verzögerungen 1–8 zeigen kein robustes Übertragungsmaximum.",
    ),
    (
        re.compile(r"Independent tracking and official estimates place China at more than 80% to about 90% of Iranian oil exports, while Iranian oil represented 13\.4% of China’s seaborne imports in Kpler’s 2025 estimate\. The dependency is asymmetric\. CENTCOM provides (\d+) core operation-day observations, but these are official U\.S\. claims rather than independent conflict-event counts\."),
        r"Unabhängiges Tracking und offizielle Schätzungen beziffern Chinas Anteil auf mehr als 80 % bis etwa 90 % der iranischen Ölexporte, während iranisches Öl nach Kplers Schätzung für 2025 13,4 % der chinesischen Seeimporte ausmachte. Die Abhängigkeit ist asymmetrisch. CENTCOM liefert \1 Beobachtungen zu Kern-Operationstagen; dabei handelt es sich jedoch um offizielle US-Angaben und nicht um unabhängige Zählungen von Konfliktereignissen.",
    ),
    (
        re.compile(r"The unusually clean Rheinmetall movement on 1–2 July is real in the stored prices, but not unique: all (\d+) of (\d+) defence companies were positive on both days and their mean two-day market-adjusted return was (.+); Rheinmetall recorded (.+)\. This supports a sector-wide component, not a sole-announcement explanation\."),
        r"Die ungewöhnlich klare Rheinmetall-Bewegung am 1.–2. Juli ist in den gespeicherten Preisen vorhanden, aber nicht einzigartig: Alle \1 von \2 Rüstungsunternehmen waren an beiden Tagen positiv; ihre mittlere zweitägige marktbereinigte Rendite betrug \3, Rheinmetall erreichte \4. Dies stützt eine sektorweite Komponente und keine Erklärung allein durch eine einzelne Ankündigung.",
    ),
    (
        re.compile(r"The Associated Press production report appeared on Sunday, 9 August, making Monday the first eligible trading day\. All four U\.S\. defence primes benchmarked to the S&P 500 were positive, averaging (.+)\. However, the fourteen non-defence S&P-benchmarked companies averaged (.+)\. The timing is plausible, but the panel does not show a defence-specific response\."),
        r"Der Produktionsbericht von Associated Press erschien am Sonntag, dem 9. August; Montag war damit der erste mögliche Handelstag. Alle vier am S&P 500 gemessenen US-Rüstungs-Hauptauftragnehmer lagen positiv und erzielten im Mittel \1. Die vierzehn am S&P 500 gemessenen Nichtrüstungsunternehmen erreichten jedoch durchschnittlich \2. Die zeitliche Abfolge ist plausibel, das Panel zeigt aber keine rüstungsspezifische Reaktion.",
    ),
    (
        re.compile(r"BlackRock itself recorded a market-adjusted CAR \[0,\+10\] of (.+) and OLS CAR of (.+)\. Its long-horizon BHAR through 18 August was (.+)\. Those descriptive returns do not support a simple claim that common holdings translated into superior performance for BlackRock shareholders\."),
        r"BlackRock selbst verzeichnete einen marktbereinigten CAR [0,+10] von \1 und einen OLS-CAR von \2. Der langfristige BHAR bis zum 18. August betrug \3. Diese deskriptiven Renditen stützen nicht die einfache Behauptung, gemeinsame Beteiligungen hätten sich in einer überlegenen Wertentwicklung für BlackRock-Aktionäre niedergeschlagen.",
    ),
    (
        re.compile(r"CSIS estimated that Patriot interceptor stocks fell from a pre-war baseline of 2,330 to 759–827 by late July, a decline of at least 65%\. This is one open-source estimate, not an official inventory count; repetition by news outlets does not create independent estimates\. AP separately reported the Pentagon’s production-acceleration request\. Product attribution is split: RTX/Raytheon supplies GEM-T, while Lockheed Martin supplies PAC-3 MSE\. The evidence therefore supports a replenishment and capacity channel relevant to both companies—not a sole-RTX demand shock and not a causal return estimate\."),
        r"CSIS schätzte, dass der Bestand an Patriot-Abfangraketen von einem Vorkriegswert von 2.330 bis Ende Juli auf 759–827 sank, ein Rückgang von mindestens 65 %. Dies ist eine einzelne Open-Source-Schätzung und keine offizielle Bestandszahl; ihre Wiederholung durch Nachrichtenmedien erzeugt keine unabhängigen Schätzungen. AP berichtete getrennt über die Aufforderung des Pentagons zur Produktionsbeschleunigung. Die Produktzuordnung ist geteilt: RTX/Raytheon liefert GEM-T, Lockheed Martin PAC-3 MSE. Die Evidenz stützt daher einen Nachbeschaffungs- und Kapazitätskanal, der für beide Unternehmen relevant ist, nicht aber einen ausschließlich RTX betreffenden Nachfrageschock oder eine kausale Renditeschätzung.",
    ),
]


if __name__ == "__main__":
    raise SystemExit(main())
